### PR TITLE
Fix bug caused by website change

### PR DESCRIPTION
**Pull request by MossyTC**
Website changed, so the plugin stopped working.

### CODE REVIEW

**Comment by AddonScriptorDE** [comment]
Thanks for the info.
I also fixed the search and cleaned some code...

**Comment by MossyTC** [comment]
You seem to have overwritten one of my pull requests that you had previously merged.

Just pointing this out in case it's not intentional.

**Comment by AddonScriptorDE** [comment]
Sorry for that - somehow the bestofyoutube repo is a bit messed up I got only errors when trying to sync this repo. Never happened before on other repos. So i endend with cloning the repo again, but it was still a bit buggy. It worked to sync now, but it always wants to commit the LICENSE.txt and fails every time. Nothing changed with that file! Maybe i just have to remove and re-add the repo...

The email request for the official repo is already out - but i will add your code to the next update...

**Comment by AddonScriptorDE** [comment]
I implemented the rating-filter in my new reddit addon:
http://forum.xbmc.org/showthread.php?tid=170603

Really useful because there are a lot more videos available/displayed.
There is also a play randomly mode...

**Pull request closed without merging**
